"""Добавлена модель шагов

Revision ID: 06c53109f24a
Revises: 5308490e96d8
Create Date: 2025-06-01 02:34:07.336210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c53109f24a'
down_revision = '5308490e96d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.Integer(), nullable=False))
        batch_op.drop_column('step_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('steps')

    # ### end Alembic commands ###
