"""Make user_id NOT NULL

Revision ID: 203658439e50
Revises: b248d4886217
Create Date: 2025-06-03 03:55:15.140670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203658439e50'
down_revision = 'b248d4886217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
