"""Добавлены поля профиля в модель User

Revision ID: 5308490e96d8
Revises: b958e64e846e
Create Date: 2025-06-01 02:25:14.859264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5308490e96d8'
down_revision = 'b958e64e846e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
