"""Убрал name из User

Revision ID: 53aed3037386
Revises: a7f0e3db632c
Create Date: 2025-06-02 01:33:31.716021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53aed3037386'
down_revision = 'a7f0e3db632c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
