"""Добавлено поле is_global к TrainingPlan

Revision ID: 72f4f4d2be85
Revises: cbc7fa1721a9
Create Date: 2025-06-04 23:12:59.977387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f4f4d2be85'
down_revision = 'cbc7fa1721a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_column('is_global')

    # ### end Alembic commands ###
